repos:
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.7.0  # Use the latest version
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
        args:
          - --types=feat,fix,docs,chore,ci,build,refactor
